import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Get Started": "Get Started",
          "Tell us about yourself":"Tell us about yourself",
          "Tell us about property":"Tell us about property",
          "I have read and accepted the rules & conditions":
              "I have read and accepted the rules & conditions",
          "Welcome!": "Welcome!",
          "Select features": "Select features",
          "A Premier Real Estate Professional.":
              "A Premier Real Estate Professional.",
          "Don't have an account?": "Don't have an account?",
          "\nAre you ready to uproot and start over in a new\narea? Placoo will help you on your journey!\n":
              "\nAre you ready to uproot and start over in a new\narea? Placoo will help you on your journey!\n",
          "New Place, New Home!": "New Place, New Home!",
          "Simplify Your Property Management":
              "Simplify Your Property Management",
          "Effortless Hosting Maximum Returns":
              "Effortless Hosting Maximum Returns",
          "Your All-in-One Rental Solution": "Your All-in-One Rental Solution",
          "Your All-in-one rental solution": "Your All-in-one rental solution",
          "Skip": "Skip",
          "Presented by Digital Oasis Real Estate\nBrokerage Company (O.P.C)":
              "Presented by Digital Oasis Real Estate\nBrokerage Company (O.P.C)",
          "Next": "Next",
          "  Register": "  Register",
          "No data found": "No data found",
          "Verified": "Verified",
          "Select Language": "Select Language",
          "Select your language": "Select your language",
          "Confirm": "Confirm",
          "Easy Rentals": "Easy Rentals",
          "Login": "Login",
          "Rent": "Rent",
          "Or": "Or",
          "See all": "See all",
          "Register": "Register",
          "Create Your Account": "Create Your Account",
          "Username": "Username",
          "Login successfully": "Login successfully",
          "Or register using": "Or register using",
          "Enter your username": "Enter your username",
          "Full Name": "Full Name",
          "Enter your name": "Enter your name",
          "Email": "Email",
          "Enter your email": "Enter your email",
          "Phone Number": "Phone Number",
          "Tutorials": "Tutorials",
          "Password": "Password",
          "Landlord": "Landlord",
          "Tenant": "Tenant",
          "Services": "Services",
          "Reset all": "Reset all",
          "All You Need": "All You Need",
          "Already have an account?": "Already have an account? ",
          "Forgot password?": "Forgot password?",
          "Don’t have an account?": "Don’t have an account? ",
          "Forget Password": "Forget Password",
          "Please enter your email address to reset your password":
              "Please enter your email address to reset your password",
          "Continue": "Continue",
          "OTP": "OTP",
          "Please enter the OTP we have sent you in your Email":
              "Please enter the OTP we have sent you in your Email",
          "Did not get the OTP?": "Did not get the OTP?",
          "Resend OTP": "Resend OTP",
          "Reset Password": "Reset Password",
          "Your password must be 8-10 characters long":
              "Your password must be 8-10 characters long",
          "Set a New Password": "Set a New Password",
          "Enter new password": "Enter new password",
          "Confirm New Password": "Confirm New Password",
          "Enter your password": "Enter your password",
          "Re-enter your password": "Re-enter your password",
          "Verify": "Verify",
          "Confirm your Identity": "Confirm your Identity",
          "Upload the Front Side of Your Civil ID":
              "Upload the Front Side of Your Civil ID",
          "Upload": "Upload",
          "Upload the Back Side of Your Civil ID":
              "Upload the Back Side of Your Civil ID",
          "Done": "Done",
          "Welcome Back!": "Welcome Back!",
          "Let’s Find Your": "Let’s Find Your",
          "Perfect Property": "Perfect Property",
          "Search for a Property": "Search for a Property",
          "Recommended": "Recommended",
          "Popular": "Popular",
          "Top Rated": "Top Rated",
          "Near You": "Near You",
          "More": "More",
          "Home": "Home",
          "Messages": "Messages",
          "Notifications": "Notifications",
          "Favorite": "Favorite",
          "Search": "Search",
          "Search Property": "Search Property",
          "Filter": "Filter",
          "Residence": "Residence",
          "Property Type": "Property Type",
          "House": "House",
          "Unverified": "Unverified",
          "Farm": "Farm",
          "Apartment": "Apartment",
          "Chalet": "Chalet",
          "Land": "Land",
          "Commercial": "Commercial",
          "Number of Rooms": "Number of Rooms",
          "Lease Term": "Lease Term",
          "Daily": "Daily",
          "Monthly": "Monthly",
          "Yearly": "Yearly",
          "Budget": "Budget",
          "Apply": "Apply",
          "View Details": "View Details",
          "Amenities": "Amenities",
          "Map": "Map",
          "Tips & Tutorials": "Tips & Tutorials",
          "4.9 (6.8K review)": "4.9 (6.8K review)",
          "Minimum Stay (1-29 days)": "Minimum Stay (1-29 days)",
          "Governorate": "Governorate",
          "Area": "Area",
          "Block": "Block",
          "Access essential tips":
              "Access essential tips, pricing advice, and management guides to boost your property’s success.",
          "Street": "Street",
          "House No.": "House No.",
          "Please enter a new password for your account.":
              "Please enter a new password for your account.",
          "Description": "Description",
          "Gallery": "Gallery",
          "Review": "Review",
          "Space": "Space",
          "Bedrooms": "Bedrooms",
          "Features": "Features",
          "Bathrooms": "Bathrooms",
          "Safety Rank": "Safety Rank",
          "About Residence": "About Residence",
          "Read more": "Read more",
          "Address": "Address",
          "View on Map": "View on Map",
          "I have read and accepted the": "I have read and accepted the ",
          "rules & conditions": "Rules & Conditions",
          "Total Price": "Total Price",
          "100 K.D /per night": "100 K.D /per night",
          "Book Now": "Book Now",
          "Minimum Stay (3+ Month)": "Minimum Stay (3+ Month)",
          "View all 172 reviews": "View all 172 reviews",
          "Check-In": "Check-In",
          "Reviews": "Reviews",
          "Select Date": "Select Date",
          "Check-Out": "Check-Out",
          "Age": "Age",
          "Day": "Day",
          "Month": "month",
          "Year": "Year",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Others": "Others",
          "Information": "Information",
          "Submit": "Submit",
          "Payment": "Payment",
          "Renting Type": "Renting Type",
          "The": " The",
          "Add Payment Method": "Add Payment Method",
          "MM/YY": "MM/YY",
          "CVV/CVC": "CVV/CVC",
          "Enter the card holder name": "Enter the card holder name",
          "Review Summary": "Review Summary",
          "Booking Date": "Booking Date",
          "Duration": "Duration",
          "Amount": "Amount",
          "Tax": "Tax",
          "Total": "Total",
          "Change": "Change",
          "Congratulations!": "Congratulations!",
          "Your Booking Has Been Successfully Completed. You can check your booking on the Profile.":
              "Your Booking Has Been Successfully Completed. You can check your booking on the Profile.",
          "Profile": "Profile",
          "Logout": "Logout",
          "Settings": "Settings",
          "Payment History": "Payment History",
          "Booking History": "Booking History",
          "Personal Information": "Personal Information",
          "Edit Profile": "Edit Profile",
          "Edit Information": "Edit Information",
          "Update": "Update",
          "Learn how to set":
              "Learn how to set competitive \nprices to maximize returns.",
          "Tips For Landlords": "Tips For Landlords",
          "My Bookings": "My Bookings",
          "Ongoing": "OnGoing",
          "Closed": "Closed",
          "Maintenance Request": "Maintenance Request",
          "Details": "Details",
          "Add Review": "Add Review",
          "Reset your password!": "Reset your password!",
          "Tax Number": "Tax Number",
          "Re-Book": "Re-Book",
          "Your overall rating of this booking":
              "Your overall rating of this booking",
          "Add Photo": "Add Photo",
          "Enter here": "Enter here",
          "Contact Now": "Contact Now",
          "Add detailed review": "Add detailed review",
          "Upload a File": "Upload a File",
          "Picture (if any)": "Picture (if any)",
          "Please enter details of requested work or a description of the problem":
              "Please enter details of requested work or a description of the problem",
          "Floor": "Floor",
          "Apartment#": "Apartment#",
          "Help?": "Help?",
          "Download Agreement": "Download Agreement",
          "Rules & Condition": "Rules & Condition",
          "Check-in Instructions": "Check-in Instructions",
          "About Landlord": "About Landlord",
          "Success": "Success",
          "Status": "Status",
          "Date": "Date",
          "Property Name": "Property Name",
          "ID Number": "ID Number",
          "Delete account": "Delete account",
          "Language": "Language",
          "Change Password": "Change Password",
          "Select": "Select",
          "Are you sure that you want to delete your account?":
              "Are you sure that you want to delete your account?",
          "Yes": "Yes",
          "No": "No",
          "Current Password": "Current Password",
          "New Password": "New Password",
          "Old Password": "Old Password",
          "Confirm new password": "Confirm new password",
          "via email:": "via email:",
          "Press continue to send an OTP to your email to reset your password":
              "Press continue to send an OTP to your email to reset your password",
          "Mark all as Read": "Mark all as Read",
          "All": "All",
          "My Subscription": "My Subscription",
          "Subscription": "Subscription",
          "Booking Request": "Booking Request",
          "Add Residences": "Add Residences",
          "My Residences": "My Residences",
          "Upload Photo": "Upload Photo",
          "Upload Video": "Upload Video",
          "Tell us about your Property": "Tell us about your Property",
          "About the property": "About the property",
          "Choose an eye-catching name":
              "Enter property name > Choose an eye-catching name",
          "Tell us about your rules & conditions":
              "Tell us about your rules & conditions",
          "Enter the number of bathrooms": "Enter the number of bathrooms",
          "Enter the number of rooms": "Enter the number of rooms",
          "Enter property space": "Enter property space",
          "Short Term": "Short Term",
          "Long Term": "Long Term",
          "Rooms": "Rooms",
          "K.D 60/Night": "K.D 60/Night",
          "Add the price of your Property": "Add the price of your Property",
          "K.D 360/Month": "K.D 360/Month",
          "Add the Rent Type": "Add the Rent Type",
          "Enter the PACI No.": "Enter the PACI No.",
          "PACI No.": "PACI No.",
          "Enter Apartment No.": "Enter Apartment No.",
          "Enter the Governorate": "Enter the Governorate",
          "Governorate*": "Governorate*",
          "Add available facilities and services":
              "Add available facilities and services",
          "Facilities": "Facilities",
          "Supermarket": "Supermarket",
          "Swimming Pool": "Swimming Pool",
          "Bath Tub": "Bath Tub",
          "Gym": "Gym",
          "Sea View": "Sea View",
          "Reception": "Reception",
          "Security": "Security",
          "Furnished": "Furnished",
          "Restaurants": "Restaurants",
          "Toiletries": "Toiletries",
          "Kitchenware": "Kitchenware",
          "Dryer": "Dryer",
          "Washer": "Washer",
          "WiFi": "WiFi",
          "Dewaniya": "Dewaniya",
          "Add More Facilities": "Add More Facilities",
          "Tell us about your check-in instructions":
              "Tell us about your check-in instructions",
          "Landlord’s Information": "Landlord’s Information",
          "About": "About",
          "About me": "About me",
          "Tell us about you": "Tell us about you",
          "Landlord Name": "Landlord Name",
          "Stand out from the crowd with paid advertising!":
              "Stand out from the crowd with paid advertising!",
          "Boost Your Ad": "Boost Your Ad",
          "Successful": "Successful",
          "Your ad has been successfully boosted":
              "Your ad has been successfully boosted",
          "Delete": "Delete",
          "Edit": "Edit",
          "Edit a property": "Edit a property",
          "Edit Video": "Edit Video",
          "Edit Photo": "Edit Photo",
          "Add New Photo": "Add New Photo",
          "Add New Video": "Add New Video",
          "Reservation details": "Reservation details",
          "Reservations list": "Reservations list",
          "See details": "See details",
          "Contact": "Contact",
          "Total Amount": "Total Amount",
          "Income": "Income",
          "Identify Verification": "Identify Verification",
          "Weekly": "Weekly",
          "Today": "Today",
          "Total Income": "Total Income",
          "Jan": "Jan",
          "Feb": "Feb",
          "Mar": "Mar",
          "Apr": "Apr",
          "May": "May",
          "Jun": "Jun",
          "Jul": "Jul",
          "Aug": "Aug",
          "Sep": "Sep",
          "Oct": "Oct",
          "Nov": "Nov",
          "Dec": "Dec",
          "Transactions": "Transactions",
          "Total Spent": "Total Spent",
          "Name": "Name",
          "Income Details": "Income Details",
          "Payment Method:": "Payment Method:",
          "Amount:": "Amount:",
          "Time & Date:": "Time & Date:",
          "Trx ID:": "Trx ID:",
          "Customer ID:": "Customer ID:",
          "Pending": "Pending",
          "Accept": "Accept",
          "Cancel": "Cancel",
          "Upgrade": "Upgrade",
          "Subscribe Now": "Subscribe Now",
          "Show less": "Show less",
          "Enter phone number": "Enter phone number",
          "Enter your address": "Enter your address",
          "Host Name": "Host Name",
          "Booking Information": "Booking Information",
          "Ads": "Ads",
          "Ads Corner": "Ads Corner",
          "Ad Details": "Ad Details",
          "Call Now": "Call Now",
          "Let's Begin The Search For": "Let's Begin The Search For",
          "The Perfect Property": "The Perfect Property",
          "Most Popular": "Most Popular",
          "Families": "Families",
          "Property": "Property",
          "Chalets": "Chalets",
          "Apartments": "Apartments",
          "Breaking The Internet": "Breaking The Internet",
          "Chat": "Chat",
          "Booking": "Booking",
          "Getting Paid": "Getting Paid",
          "My Subscriptions": "My Subscriptions",
          "My Listings": "My Listings",
          "Add Listings": "Add Listings",
          "New Booking": "New Booking",
          "Payments": "Payments",
          "Complete Registration": "Complete Registration!",
          "Nationality": "Nationality",
          "Select your nationality": "Select your nationality",
          "Marital Status": "Marital Status",
          "Select your marital status": "Select your marital status",
          "Single": "Single",
          "Married": "Married",
          "Divorced": "Divorced",
          "Widowed": "Widowed",
          "Separated": "Separated",
          "Date of Birth": "Date of Birth",
          "Job": "Job",
          "Enter your job title": "Enter your job title",
          "Monthly Income": "Monthly Income",
          "Select your income bracket": "Select your income bracket",
          "Under 800 KD": "Under 800 KD",
          "Between 800 - 1499 KD": "Between 800 - 1499 KD",
          "Between 1500 - 3000 KD": "Between 1500 - 3000 KD",
          "Over 3000 KD": "Over 3000 KD",
          "I confirm that the information provided is truthful and accurate":
              "I confirm that the information provided is truthful and accurate",
          "I have read and accepted the Terms and Conditions":
              "I have read and accepted the Terms and Conditions",
          "Identity Verification Page": "Identity Verification Page",
          "Verify Your Identity": "Verify Your Identity",
          "Enhance Trust with Verified ID!": "Enhance Trust with Verified ID!",
          "Secure your profile with our robust ID verification system and show others that you're serious about safety and reliability.":
              "Secure your profile with our robust ID verification system and show others that you're serious about safety and reliability.",
          "Upload Your Documents": "Upload Your Documents",
          "Front Side of Your ID (or Passport)":
              "Front Side of Your ID (or Passport)",
          "Back Side of Your ID": "Back Side of Your ID",
          "I certify that the documents I have provided are original and accurate":
              "I certify that the documents I have provided are original and accurate",
          "Excellent!": "Excellent!",
          "You've verified your ID!": "You've verified your ID!",
          "Your profile is now more secure and trustworthy. Your verification will be confirmed within the next 24 hours. We appreciate your commitment to safety and integrity.":
              "Your profile is now more secure and trustworthy. Your verification will be confirmed within the next 24 hours. We appreciate your commitment to safety and integrity.",
          "Getting Paid Page": "Getting Paid Page",
          "Country": "Country",
          "Enter your full name": "Enter your full name",
          "Select your country": "Select your country",
          "Beneficiary’s Full Name": "Beneficiary’s Full Name",
          "Enter your full name in English": "Enter your full name in English",
          "Bank Name": "Bank Name",
          "Enter your bank name": "Enter your bank name",
          "Swift Code (international accounts only)":
              "Swift Code (international accounts only)",
          "Enter your bank’s swift code": "Enter your bank’s swift code",
          "IBAN / Account Number": "IBAN / Account Number",
          "Enter your bank account / IBAN No.":
              "Enter your bank account / IBAN No.",
          "Beneficiary’s Address": "Beneficiary’s Address",
          "Disclaimer!": "Disclaimer!",
          "You are responsible for the accuracy of the bank details you have provided. We are not liable for any errors that may cause delays or cancellations of transferred funds":
              "You are responsible for the accuracy of the bank details you have provided. We are not liable for any errors that may cause delays or cancellations of transferred funds",
          "Booking Requests Page": "Booking Requests Page",
          "Decline": "Decline",
          "Are you sure that you want to decline this booking request?":
              "Are you sure that you want to decline this booking request?",
          "Confirmation": "Confirmation",
          "Resend the OTP again via whatsapp?":
              "Resend the OTP again via whatsapp?",
          "Booking Confirmed!": "Booking Confirmed!",
          "Congratulations! This booking has been confirmed. Please prepare the property and be available for any questions your guest may have.":
              "Congratulations! This booking has been confirmed. Please prepare the property and be available for any questions your guest may have.",
          "Thank you for being a valued member. Contact support if you need assistance.":
              "Thank you for being a valued member. Contact support if you need assistance.",
          "Happy Hosting!": "Happy Hosting!",
          "No review found": "No review found",
          "Best regards,": "Best regards,",
          "The Mosta’ajer App Team": "The Mosta’ajer App Team",
          "Top Picks": "Top Picks",
          "Personal Details": "Personal Details",
          "internet_exception": "No Internet Connection",
          "general_exception": "Some error occoured\nPlease try again",
          "Just Listed": "Just Listed",
        },
        'ar_SA': {
          "Get Started": "إبدأ الآن",
          "Simplify Your Property Management": "بسط إدارة ممتلكاتك",
          "Effortless Hosting Maximum Returns": "استضافة سهلة، عوائد قصوى",
          "Your All-in-One Rental Solution": "حلك الشامل للتأجير",
          "Skip": "تخطي",
          "Next": "التالي",
          "Select Language": "اختر اللغة",
          "Confirm": "تأكيد",
          "Easy Rentals": "إيجارات سهلة",
          "Login": "دخول",
          "Rent": "إيجار",
          "No review found": "لم يتم العثور على أي تعليقات.",
          "Register": "تسجيل",
          "Create Your Account": "إنشاء حساب",
          "Username": "اسم المستخدم",
          "Enter your username": "ادخل اسم المستخدم هنا",
          "Full Name": "الاسم الكريم",
          "Enter your name": "ادخل اسمك هنا",
          "Email": "البريد الإلكتروني",
          "Enter your email": "ادخل بريدك الإلكتروني هنا",
          "Phone Number": "رقم الهاتف",
          "Password": "كلمة المرور",
          "Landlord": "مالك العقار",
          "Tenant": "مستأجر",
          "Already have an account?": " هل لديك حساب؟",
          "Forgot password?": "هل نسيت كلمة المرور؟",
          "Don’t have an account?": "ليس لديك حساب؟",
          "Forget Password": "نسيت كلمة المرور",
          "Please enter your email address to reset your password":
              "يرجى إدخال بريدك الإلكتروني لإعادة تعيين كلمة المرور",
          "Continue": "متابعة",
          "OTP": "رمز التحقق",
          "Please enter the OTP we have sent you in your Email":
              "يرجى إدخال رمز التحقق المرسل إلى بريدك الإلكتروني",
          "Did not get the OTP?": "لم تستلم رمز التحقق؟",
          "Resend OTP": "إعادة إرسال رمز التحقق",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Your password must be 8-10 characters long":
              "يجب أن تتكون كلمة المرور من 8-10 أحرف",
          "Set a New Password": "تعيين كلمة مرور جديدة",
          "Enter new password": "أدخل كلمة المرور الجديدة",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Enter your password": "ادخل رقمك السري",
          "Re-enter your password": "أعد إدخال كلمة المرور",
          "Verify": "تحقق",
          "Confirm your Identity": "تأكيد هويتك",
          "Upload the Front Side of Your Civil ID":
              "تحميل الجانب الأمامي من بطاقة الهوية المدنية",
          "Upload": "تحميل",
          "Upload the Back Side of Your Civil ID":
              "تحميل الجانب الخلفي من بطاقة الهوية المدنية",
          "Done": "تم",
          "Features": "ميزات",
          "Select features": "اختر الميزات",
          "Let’s Find Your": "دعونا نجد الخاص بك",
          "Perfect Property": "ملكية مثالية",
          "Search for a Property": "البحث عن عقار",
          "Recommended": "موصى به",
          "Popular": "شائع",
          "Resend the OTP again via whatsapp?":
              "أعد إرسال رمز التحقق عبر واتساب؟",
          "Top Rated": "الأعلى تقييماً",
          "Near You": "بالقرب منك",
          "More": "المزيد",
          "Home": "الرئيسية",
          "Messages": "الرسائل",
          "Notifications": "الإشعارات",
          "Favorite": "المفضلة",
          "Search": "بحث",
          "Search Property": "بحث عن عقار",
          "Filter": "تصفية",
          "Property Type": "نوع العقار",
          "Property": "العقار",
          "House": "منزل",
          "Farm": "مزرعة",
          "Apartment": "شقة",
          "Chalet": "شاليه",
          "Land": "أرض",
          "Commercial": "تجاري",
          "Number of Rooms": "عدد الغرف",
          "Lease Term": "مدة الإيجار",
          "Daily": "يومي",
          "Monthly": "شهري",
          "Yearly": "سنوي",
          "Budget": "الميزانية",
          "Apply": "تطبيق",
          "Map": "خريطة",
          "4.9 (6.8K review)": "4.9 (6.8K مراجعة)",
          "Minimum Stay (1-29 days)": "مدة الإقامة الدنيا (1-29 يوم)",
          "Governorate": "المحافظة",
          "Area": "المنطقة",
          "Block": "القطعة",
          "Street": "الشارع",
          "House No.": "رقم المنزل",
          "Description": "الوصف",
          "Gallery": "المعرض",
          "Review": "التقييم",
          "Space": "المساحة",
          "Bedrooms": "غرف النوم",
          "Bathrooms": "الحمامات",
          "Safety Rank": "تصنيف الأمان",
          "About Residence": "عن الإقامة",
          "Residence": "الإقامة",
          "Read more": "اقرأ المزيد",
          "Address": "العنوان",
          "View on Map": "عرض على الخريطة",
          "I have read and accepted the": "لقد قرأت وقبلت",
          "rules & conditions": "القواعد والشروط",
          "Total Price": "السعر الإجمالي",
          "100 K.D /per night": "100 د.ك /لليلة",
          "Book Now": "احجز الآن",
          "Minimum Stay (3+ Month)": "مدة الإقامة الدنيا (3+ أشهر)",
          "View all 172 reviews": "عرض جميع 172 التقييمات",
          "Check-In": "تسجيل الدخول",
          "Select Date": "اختر التاريخ",
          "Check-Out": "تسجيل الخروج",
          "Age": "العمر",
          "Day": "اليوم",
          "Month": "الشهر",
          "Year": "السنة",
          "Gender": "الجنس",
          "Male": "ذكر",
          "Female": "أنثى",
          "Others": "أخرى",
          "Information": "المعلومات",
          "Submit": "إرسال",
          "Reviews": "مراجعات",
          "Payment": "الدفع",
          "Add Payment Method": "إضافة طريقة الدفع",
          "MM/YY": "شهر/سنة",
          "CVV/CVC": "رمز التحقق",
          "Enter the card holder name": "أدخل اسم حامل البطاقة",
          "Review Summary": "ملخص التقييم",
          "Booking Date": "تاريخ الحجز",
          "Duration": "المدة",
          "Amount": "المبلغ",
          "Tax": "الضريبة",
          "Total": "الإجمالي",
          "Change": "تغيير",
          "Congratulations!": "مبروك!",
          "Your Booking Has Been Successfully Completed. You can check your booking on the Profile.":
              "تم إكمال حجزك بنجاح. يمكنك التحقق من حجزك في الملف الشخصي.",
          "Profile": "الملف الشخصي",
          "Logout": "تسجيل الخروج",
          "Settings": "الإعدادات",
          "Payment History": "سجل المدفوعات",
          "Booking History": "سجل الحجز",
          "Personal Information": "المعلومات الشخصية",
          "Edit Profile": "تعديل الملف الشخصي",
          "Edit Information": "تعديل المعلومات",
          "Update": "تحديث",
          "My Bookings": "حجوزاتي",
          "Ongoing": "جارية",
          "Closed": "مغلقة",
          "Maintenance Request": "طلب صيانة",
          "Details": "التفاصيل",
          "Add Review": "إضافة تقييم",
          "Re-Book": "إعادة الحجز",
          "Your overall rating of this booking": "تقييمك العام لهذا الحجز",
          "Add Photo": "إضافة صورة",
          "Enter here": "أدخل هنا",
          "Add detailed review": "إضافة تقييم مفصل",
          "Upload a File": "رفع ملف",
          "Picture (if any)": "صورة (إذا كان هناك)",
          "Please enter details of requested work or a description of the problem":
              "يرجى إدخال تفاصيل العمل المطلوب أو وصف المشكلة",
          "Floor": "الطابق",
          "Apartment#": "شقة رقم",
          "Help?": "مساعدة؟",
          "Download Agreement": "تحميل الاتفاقية",
          "Rules & Condition": "القواعد والشروط",
          "Check-in Instructions": "تعليمات تسجيل الدخول",
          "About Landlord": "عن المالك",
          "Success": "نجاح",
          "Status": "الحالة",
          "Date": "التاريخ",
          "Property Name": "اسم العقار",
          "ID Number": "رقم الهوية",
          "Delete account": "حذف الحساب",
          "Language": "اللغة",
          "Change Password": "تغيير كلمة المرور",
          "Select": "اختر",
          "Are you sure that you want to delete your account?":
              "هل أنت متأكد من أنك تريد حذف حسابك؟",
          "Yes": "نعم",
          "No": "لا",
          "Current Password": "كلمة المرور الحالية",
          "New Password": "كلمة مرور جديدة",
          "Old Password": "كلمة السر القديمة",
          "Confirm new password": "تأكيد كلمة المرور الجديدة",
          "via email:": "عبر البريد الإلكتروني:",
          "Press continue to send an OTP to your email to reset your password":
              "اضغط متابعة لإرسال رمز التحقق إلى بريدك الإلكتروني لإعادة تعيين كلمة المرور",
          "Mark all as Read": "وضع علامة مقروءة على الكل",
          "All": "الكل",
          "Tips & Tutorials": "إرشادات ونصائح",
          "My Subscription": "اشتراكاتي",
          "Subscription": "اشتراك",
          "Booking Request": "طلب حجز",
          "Add Residences": "إضافة عقار",
          "My Residences": "عقاراتي",
          "Learn how to set":
              "تعرف على كيفية تحديد أسعار\n تنافسية لتحقيق أقصى قدر من العائدات",
          "Upload Photo": "تحميل صورة",
          "Upload Video": "تحميل فيديو",
          "Tell us about your Property": "أخبرنا عن عقارك",
          "About the property": "عن العقار",
          "Choose an eye-catching name": "اختر اسم ملفت للنظر",
          "Tell us about your rules & conditions":
              "أخبرنا عن القواعد والشروط الخاصة بك",
          "Enter the number of bathrooms": "ادخل عدد الحمامات",
          "Enter the number of rooms": "ادحل عدد الغرف",
          "Enter property space": "ادخل مساحة العقار",
          "Short Term": "تأجير قصير المدى",
          "Long Term": "تأجير طويل المدى",
          "K.D 60/Night": "60 د.ك/لليلة الواحدة",
          "Add the price of your Property": "اضف سعر عقارك",
          "K.D 360/Month": "360 د.ك/شهري",
          "Add the Rent Type": "ادخل نوع الايجار",
          "Enter the PACI No.": "ادخل الرقم الآلي للعنوان",
          "PACI No.": "الرقم الآلي للعنوان",
          "Enter Apartment No.": "ادخل رقم الشقة",
          "Enter the Floor No.": "ادخل رقم الطابق",
          "Enter the house/building number": "ادخل رقم المنزل/المبنى",
          "House/Building": "المنزل/المبنى",
          "Enter the address of the property": "ادخل عنوان العقار",
          "Enter the area name": "",
          "Enter the Governorate": "",
          "Governorate*": "المحافظة",
          "Add available facilities and services":
              "أضف المرافق والخدمات المتاحة",
          "Facilities": "مرافق",
          "Supermarket": "بقالة",
          "Swimming Pool": "مسبح",
          "Bath Tub": "جاكوزي",
          "Gym": "نادي",
          "Sea View": "إطلالة بحرية",
          "Reception": "إستقبال",
          "Security": "حراسة",
          "Furnished": "مفروشة",
          "Amenities": "ميزات",
          "Restaurants": "مطاعم",
          "Toiletries": "مستلزمات الحمام",
          "Kitchenware": "أدوات المطبخ",
          "Dryer": "نشافة",
          "Washer": "غسالة",
          "WiFi": "واي فاي",
          "Tutorials": "دروس",
          "Dewaniya": "ديوانية",
          "Add More Facilities": "إضافة المزيد من المرافق",
          "Tell us about your check-in instructions":
              "أخبرنا عن تعليمات تسجيل الوصول الخاصة بك",
          "Landlord’s Information": "معلومات المالك",
          "About": "عن",
          "About me": "عني",
          "View Details": "عرض التفاصيل",
          "Tell us about you": "أخبرنا عن نفسك",
          "Landlord Name": "اسم المؤجر",
          "Stand out from the crowd with paid advertising!":
              "تميز عن الآخرين من خلال خدمة الإعلانات المدفوعة!",
          "Boost Your Ad": "قم بترقيتك إعلانك",
          "Successful": "تم بنجاح",
          "Your ad has been successfully boosted": "لقد تم ترقية إعلانك بنجاح",
          "Delete": "حذف",
          "Edit": "تعديل",
          "Edit a property": "تعديل عقار",
          "Edit Video": "تعديل الفيديو",
          "Edit Photo": "تعديل الصورة",
          "Add New Photo": "إضافة صورة جديدة",
          "Add New Video": "إضافة فيديو جديد",
          "Reservation details": "تفاصيل الحجز",
          "Reservations list": "قائمة الحجوزات",
          "See details": "رؤية التفاصيل",
          "Reset your password!": "إعادة تعيين كلمة السر!",
          "Please enter a new password for your account.":
              "الرجاء إدخال كلمة سر جديدة لحسابك",
          "Contact": "التواصل",
          "Total Amount": "المبلغ الإجمالي",
          "Income": "الدخل",
          "See all": "انظر الكل",
          "Identify Verification": "التحقق من الهوية",
          "Weekly": "اسبوعي",
          "Today": "اليوم",
          "Tax Number": "الرقم الضريبي",
          "Login successfully": "تم الدخول بنجاح",
          "Total Income": "إجمالي الدخل",
          "Jan": "يناير",
          "Feb": "فبراير",
          "Mar": "مارس",
          "Apr": "ابريل",
          "May": "مايو",
          "Jun": "يونيو",
          "Jul": "يوليو",
          "Aug": "اغسطس",
          "Sep": "سبتمبر",
          "Oct": "اكتوبر",
          "Nov": "نوفمبر",
          "Dec": "ديسمبر",
          "Transactions": "المعاملات",
          "Total Spent": "إجمالي الإنفاق",
          "Name": "الاسم",
          "Features": "سمات",
          "Income Details": "تفاصيل الدخل",
          "Payment Method:": "طريقة الدفع:",
          "Amount:": "المبلغ:",
          "Or register using": "أو سجل بإستخدام",
          "Time & Date:": "الوقت والتاريخ:",
          "Trx ID:": "رقم المعاملة:",
          "Customer ID:": "رقم العميل:",
          "Pending": "معلق",
          "Accept": "قبول",
          "Cancel": "إلغاء",
          "Or": "أو",
          "Upgrade": "ترقية",
          "Tips For Landlords": "نصائح لملاك العقارات",
          "Subscribe Now": "اشترك الآن",
          "Show less": "عرض أقل",
          "Enter phone number": "أدخل رقم الهاتف",
          "Enter your address": "أدخل عنوان الهاتف",
          "Host Name": "اسم المضيف",
          "Booking Information": "معلومات الحجز",
          "Ads": "إعلانات",
          "Ads Corner": "ركن الإعلانات",
          "Ad Details": "تفاصيل الإعلان",
          "Call Now": "اتصل الان",
          "Let's Begin The Search For": "لنبدأ رحلة البحث عن",
          "The Perfect Property": "العقار المثالي",
          "Most Popular": "الأكثر شعبية",
          "Families": "للعائلات",
          "Access essential tips":
              "احصل على نصائح مهمة حول التسعير وإدارة عقارك للحصول على تجربة إيجار ناجحة",
          "Chalets": "شاليهات",
          "Apartments": "شقق",
          "Breaking The Internet": "مكسر الدنيا",
          "Chat": "الدردشة",
          "Booking": "حجوزاتي",
          "Getting Paid": "تحصيل الأموال",
          "My Subscriptions": "اشتراكاتي",
          "My Listings": "إعلاناتي",
          "Add Listings": "إضافة إعلان",
          "New Booking": "حجز جديد",
          "Payments": "مدفوعاتي",
          "Complete Registration": "أكمل التسجيل",
          "Nationality": "الجنسية",
          "Select your nationality": "اختر جنسيتك",
          "Marital Status": "الحالة الاجتماعية",
          "Select your marital status": "اختر حالتك الاجتماعية",
          "Single": "أعزب",
          "Married": "متزوج",
          "Reset all": "إعادة تعيين الكل",
          "Divorced": "مطلق",
          "Widowed": "أرمل",
          "Separated": "منفصل",
          "Date of Birth": "تاريخ الميلاد",
          "Job": "الوظيفة",
          "Enter your job title": "ادخل تفاصيل عملك",
          "Monthly Income": "الدخل الشهري",
          "Select your income bracket": "حدد شريحة الدخل",
          "Under 800 KD": "أقل من 800 د.ك",
          "Between 800 - 1499 KD": "بين 800 - 1499 د.ك",
          "Between 1500 - 3000 KD": "بين 1500 - 3000 د.ك",
          "Over 3000 KD": "أكثر من 3000",
          "I confirm that the information provided is truthful and accurate":
              "أنا أقر بصحة ودقة البيانات التي قمت بإدخالها",
          "I have read and accepted the Terms and Conditions":
              "لقد قرأت وأوافق على الشروط والأحكام",
          "Identity Verification Page": "صفحة التحقق من الهوية",
          "Verify Your Identity": "قم بتأكيد هويتك",
          "Enhance Trust with Verified ID!": "عزز الثقة مع التحقق من الهوية!",
          "Secure your profile with our robust ID verification system and show others that you're serious about safety and reliability.":
              "قم بتأمين ملفك الشخصي بنظام التحقق من الهوية القوي لدينا وأظهر للآخرين أنك جاد بشأن السلامة والموثوقية.",
          "Upload Your Documents": "قم بتحميل المستندات",
          "Front Side of Your ID (or Passport)":
              "الجانب الأمامي من هويتك (أو جواز السفر)",
          "Back Side of Your ID": "الجانب الخلفي من هويتك",
          "I certify that the documents I have provided are original and accurate":
              "أنا أقر بأن المستندات التي قدمتها أصلية ودقيقة",
          "Excellent!": "ممتاز!",
          "You've verified your ID!": "لقد تم التحقق من هويتك!",
          "Your profile is now more secure and trustworthy. Your verification will be confirmed within the next 24 hours. We appreciate your commitment to safety and integrity.":
              "ملفك الشخصي الآن أكثر أمانًا وموثوقية. سيتم تأكيد التحقق من هويتك خلال الـ 24 ساعة القادمة. نحن نقدر التزامك بالسلامة والنزاهة.",
          "Getting Paid Page": "صفحة الحصول على الدفع",
          "Country": "الدولة",
          "Select your country": "اختر دولتك",
          "Beneficiary’s Full Name": "اسم المستفيد بالكامل",
          "Enter your full name in English": "ادخل اسمك الكامل بالإنجليزية",
          "Bank Name": "اسم البنك",
          "Enter your full name": "ادخل اسمك الكامل",
          "Enter your bank name": "ادخل اسم البنك",
          "I have read and accepted the rules & conditions":
              "لقد قرأت وقبلت القواعد والشروط",
          "Swift Code (international accounts only)":
              "رمز البنك (الحسابات الدولية فقط)",
          "Enter your bank’s swift code": "ادخل رمز البنك (السويفت)",
          "IBAN / Account Number": "رقم الآيبان / الحساب",
          "Enter your bank account / IBAN No.": "ادخل رقم الآيبان / الحساب",
          "Beneficiary’s Address": "عنوان المستفيد",
          "Tell us about property":"أخبرنا عن العقار",
          "Disclaimer!": "تنبيه!",
          "You are responsible for the accuracy of the bank details you have provided. We are not liable for any errors that may cause delays or cancellations of transferred funds":
              "أنت مسؤول عن دقة تفاصيل الحساب البنكي التي تقدمها. نحن غير مسؤولين عن أي أخطاء قد تسبب تأخيرًا أو إلغاءً للتحويلات المالية.",
          "Booking Requests Page": "صفحة طلبات الحجز",
          "Decline": "رفض",
          "  Register": "  يسجل",
          "Are you sure that you want to decline this booking request?":
              "هل أنت متأكد من رغبتك برفض طلب الحجز؟",
          "Confirmation": "تأكيد",
          "Booking Confirmed!": "تم تأكيد الحجز!",
          "Congratulations! This booking has been confirmed. Please prepare the property and be available for any questions your guest may have.":
              "مبروك! لقد تم تأكيد هذا الحجز. يرجى إعداد مكان الإقامة والتواجد للرد على أية أسئلة قد تكون لدى ضيفك.",
          "Thank you for being a valued member. Contact support if you need assistance.":
              "شكرا لكونك عضو قيم في عائلتنا. اتصل بالدعم إذا كنت بحاجة إلى المساعدة.",
          "Happy Hosting!": "تمنياتنا باستضافة سعيدة!",
          "Best regards,": "أطيب التحيات،",
          "The Mosta’ajer App Team": "فريق عمل تطبيق مستأجر",
          "Top Picks": "أفضل اللقطات",
          "Just Listed": "مدرج للتو",
          "Personal Details": "التفاصيل الشخصية",
          "Unverified": "لم يتم التحقق منها",
          "Verified": "تم التحقق منه",
          "Services": "خدمات",
          "All You Need": "كل ما تحتاجه",
          "Contact Now": "اتصل الآن",
          "Welcome!": "مرحباً!",
          "The": "ال",
          "Renting Type": "نوع الإيجار",
          "Tell us about yourself":"أخبرنا عن نفسك",
          "Rooms": "الغرف",
          "Don't have an account?": "ليس لديك حساب؟",
          "A Premier Real Estate Professional.": "محترف عقاري متميز.",
          "Welcome Back!": "مرحبًا بعودتك!",
          "Log In to your Placoo account to explore your dream place to live across the whole world!":
              "قم بتسجيل الدخول إلى حساب Placoo الخاص بك لاستكشاف مكان أحلامك للعيش فيه في جميع أنحاء العالم!",
          "No data found": "لم يتم العثور على بيانات",
          "Your All-in-one rental solution": "حل الإيجار الشامل الخاص بك",
          "Select your language": "اختر لغتك",
          "Presented by Digital Oasis Real Estate\nBrokerage Company (O.P.C)":
              "مقدمة من شركة الواحة الرقمية العقارية\nشركة الوساطة المالية (O.P.C)",
          "New Place, New Home!": "مكان جديد، منزل جديد!",
          "\nAre you ready to uproot and start over in a new\narea? Placoo will help you on your journey!\n":
              "\nهل أنت مستعد لاقتلاع جذورك والبدء من جديد في منطقة\n جديدة؟ سوف يساعدك Placoo في رحلتك!\n"
        },
      };
}
