// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfW3u5przE9WGkMr7v63O9anAoCoijLzw',
    appId: '1:500939881259:web:e7332b94ff5ac4dd37e36e',
    messagingSenderId: '500939881259',
    projectId: 'real-state-e9a88',
    authDomain: 'real-state-e9a88.firebaseapp.com',
    storageBucket: 'real-state-e9a88.appspot.com',
    measurementId: 'G-SDVS4FWT45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFs5wOHZx9BvQMbYovOnGGf_Di59OVFjk',
    appId: '1:500939881259:android:211d6c89a08a8c0037e36e',
    messagingSenderId: '500939881259',
    projectId: 'real-state-e9a88',
    storageBucket: 'real-state-e9a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwQN26soh-vcwhIig2dMsMvjWd_H2Ri5U',
    appId: '1:500939881259:ios:e20e5b0f51bb3abb37e36e',
    messagingSenderId: '500939881259',
    projectId: 'real-state-e9a88',
    storageBucket: 'real-state-e9a88.appspot.com',
    iosBundleId: 'com.example.realEstateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwQN26soh-vcwhIig2dMsMvjWd_H2Ri5U',
    appId: '1:500939881259:ios:e20e5b0f51bb3abb37e36e',
    messagingSenderId: '500939881259',
    projectId: 'real-state-e9a88',
    storageBucket: 'real-state-e9a88.appspot.com',
    iosBundleId: 'com.example.realEstateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfW3u5przE9WGkMr7v63O9anAoCoijLzw',
    appId: '1:500939881259:web:34510efe7c2bcb0037e36e',
    messagingSenderId: '500939881259',
    projectId: 'real-state-e9a88',
    authDomain: 'real-state-e9a88.firebaseapp.com',
    storageBucket: 'real-state-e9a88.appspot.com',
    measurementId: 'G-882C8M9ECN',
  );
}
